	var __wxAppData = __wxAppData || {}; 	var __wxRoute = __wxRoute || ""; 	var __wxRouteBegin = __wxRouteBegin || ""; 	var __wxAppCode__ = __wxAppCode__ || {};	var global = global || {};	var __WXML_GLOBAL__=__WXML_GLOBAL__ || {};	var __wxAppCurrentFile__=__wxAppCurrentFile__||""; 	var Component = Component || function(){};	var definePlugin = definePlugin || function(){};	var requirePlugin = requirePlugin || function(){};	var Behavior = Behavior || function(){};
	
	define("config.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";var t="www.qiying001.com",s={service:{host:t,loginUrl:"https://"+t+"/WeApp/Index/login",requestUrl:"https://"+t+"/user",tunnelUrl:"https://"+t+"/tunnel"},host:"https://"+t+"/",imgPre:"https://qyzxpic.oss-cn-beijing.aliyuncs.com/"};module.exports=s; 
 			}); 
		define("utils/constants.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";module.exports={WX_HEADER_CODE:"X-WX-Code",WX_HEADER_ENCRYPTED_DATA:"X-WX-Encrypted-Data",WX_HEADER_IV:"X-WX-IV",WX_HEADER_ID:"X-WX-Id",WX_HEADER_SKEY:"X-WX-Skey",WX_SESSION_MAGIC_ID:"F2C224D4-2BCE-4C64-AF9F-A6D872000D1A",ERR_INVALID_PARAMS:"ERR_INVALID_PARAMS",ERR_WX_LOGIN_FAILED:"ERR_WX_LOGIN_FAILED",ERR_WX_GET_USER_INFO:"ERR_WX_GET_USER_INFO",ERR_LOGIN_TIMEOUT:"ERR_LOGIN_TIMEOUT",ERR_LOGIN_FAILED:"ERR_LOGIN_FAILED",ERR_LOGIN_SESSION_NOT_RECEIVED:"ERR_LOGIN_MISSING_SESSION",ERR_INVALID_SESSION:"ERR_INVALID_SESSION",ERR_CHECK_LOGIN_FAILED:"ERR_CHECK_LOGIN_FAILED"}; 
 			}); 
		define("utils/default.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";var a=require("util.js"),t=getApp();module.exports={data:{userInfo:{},lawyer:{}},onLoad:function(){var e=this;a.isEmpty(t.globalData.lawyer)?t.getLawyerData(function(a){e.setData({lawyer:a})}):this.setData({lawyer:t.globalData.lawyer}),t.getUserInfo(function(a){e.setData({userInfo:a})})},onShareAppMessage:function(){return{title:t.globalData.lawyer.name,desc:t.globalData.lawyer.about}},gotomap:function(){t.getServerInfo("Map/api/getMapInfo",{},function(t){var e=t.data.coords;console.log(e);var o=e.split(","),n=a.bd_decrypt(o[0],o[1]);wx.openLocation({latitude:n.gg_lat,longitude:n.gg_lon,scale:28,name:t.data.name,address:t.data.address,success:function(a){},fail:function(){},complete:function(){}})})}}; 
 			}); 
		define("utils/login.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";var e=require("./util"),s=require("./constants"),n=require("./session"),i=require("../config"),o=function(){function e(e,s){Error.call(this,s),this.type=e,this.message=s}return e.prototype=new Error,e.prototype.constructor=e,e}(),r=function(e){wx.login({success:function(s){e(null,{code:s.code,encryptedData:"",iv:"",userInfo:{avatarUrl:i.host+"Public/template/headImgUrl.jpg",nickName:"匿名用户"}})},fail:function(n){var i=new o(s.ERR_WX_LOGIN_FAILED,"微信登录失败，请检查网络状态");i.detail=n,e(i,null)}})},t=function(){},a={method:"GET",success:t,fail:t,loginUrl:i.service.loginUrl,data:{}};module.exports={LoginError:o,login:function(i){if(i=e.extend({},a,i),a.loginUrl){var t=function(){return r(function(e,r){if(e)i.fail(e);else{var t=r.userInfo,a=r.code,c=r.encryptedData,l=r.iv,u={};i.data.code=a,i.data.iv=l,i.data.data=c,wx.request({url:i.loginUrl,header:u,method:i.method,data:i.data,success:function(e){var r=e.data;if(r.session={},r&&0==r.errcode)if(r.session_id)r.session.userInfo=t,r.session.session_id=r.session_id,r.session.wxid=r.wxid,n.set(r.session),i.success(t);else{var a="登录失败("+r.error+")："+(r.message||"未知错误"),c=new o(s.ERR_LOGIN_SESSION_NOT_RECEIVED,a);i.fail(c)}else{var a="登录请求没有包含会话响应，请确保服务器处理 `"+i.loginUrl+"` 的时候正确使用了 SDK 输出登录结果",c=new o(s.ERR_LOGIN_SESSION_NOT_RECEIVED,a);i.fail(c)}},fail:function(e){var n=new o(s.ERR_LOGIN_FAILED,"登录失败，可能是网络错误或者服务器发生异常");i.fail(n)}})}})},c=n.get();c?wx.checkSession({success:function(){i.success(c.userInfo)},fail:function(){n.clear(),t()}}):t()}else i.fail(new o(s.ERR_INVALID_PARAMS,"登录错误：缺少登录地址，请通过 setLoginUrl() 方法设置登录地址"))},setLoginUrl:function(e){a.loginUrl=e}}; 
 			}); 
		define("utils/request.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";var e="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(e){return typeof e}:function(e){return e&&"function"==typeof Symbol&&e.constructor===Symbol&&e!==Symbol.prototype?"symbol":typeof e},o=require("./constants"),r=require("./util"),n=require("./session"),t=require("./login"),i=function(){},u=function(e){var o={};return e&&e.session_id&&(o.Cookie="PHPSESSID="+e.session_id),o},c=function(){function e(e,o){Error.call(this,o),this.type=e,this.message=o}return e.prototype=new Error,e.prototype.constructor=e,e}();module.exports={RequestError:c,request:function(l){function s(){t.login({success:f,fail:S})}function f(){var e=u(n.get());wx.request(r.extend({},l,{header:r.extend({},v,e),success:function(e){var o=e.data;if(o&&o.errcode>=8){n.clear();var r,t;if(9==o.errcode){if(!q)return q=!0,void s();t="登录态已过期",r=new c(o.errcode,t)}else t="鉴权服务器检查登录态发生错误("+(o.errcode||"OTHER")+")："+(o.msg||"未知错误"),r=new c(o.errcode,t);S(r)}else b.apply(null,arguments)},fail:S,complete:i}))}if("object"!==(void 0===l?"undefined":e(l))){var a="请求传参应为 object 类型，但实际传了 "+(void 0===l?"undefined":e(l))+" 类型";throw new c(o.ERR_INVALID_PARAMS,a)}var p=l.login,d=l.success||i,y=l.fail||i,m=l.complete||i,v=l.header||{},b=function(){d.apply(null,arguments),m.apply(null,arguments)},S=function(e){y.call(null,e),m.call(null,e)},q=!1;p?s():f()}}; 
 			}); 
		define("utils/session.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";var e="weapp_session_"+require("./constants").WX_SESSION_MAGIC_ID,t={get:function(){return wx.getStorageSync(e)||null},set:function(t){wx.setStorageSync(e,t)},clear:function(){wx.removeStorageSync(e)}};module.exports=t; 
 			}); 
		define("utils/util.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";function t(t){return(t=t.toString())[1]?t:"0"+t}function e(t){for(var r=Array.prototype.slice.call(arguments,1),o=0;o<r.length;o+=1){var a=r[o];for(var s in a)"object"!==n(t[s])?t[s]=a[s]:"object"===n(a[s])?e(t[s],a[s]):a.hasOwnProperty(s)&&(t[s]=a[s])}return t}var n="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(t){return typeof t}:function(t){return t&&"function"==typeof Symbol&&t.constructor===Symbol&&t!==Symbol.prototype?"symbol":typeof t},r=require("../config");module.exports={formatTime:function(e){var n=e.getFullYear(),r=e.getMonth()+1,o=e.getDate(),a=e.getHours(),s=e.getMinutes(),i=e.getSeconds();return[n,r,o].map(t).join("/")+" "+[a,s,i].map(t).join(":")},isEmpty:function(t){for(var e in t)return!1;return!0},bd_decrypt:function(t,e){var n=3e3*Math.PI/180,r=t-.0065,o=e-.006,a=Math.sqrt(r*r+o*o)-2e-5*Math.sin(o*n),s=Math.atan2(o,r)-3e-6*Math.cos(r*n);return{gg_lon:a*Math.cos(s),gg_lat:a*Math.sin(s)}},bd_encrypt:function(t,e){var n=3e3*Math.PI/180,r=t,o=e,a=Math.sqrt(r*r+o*o)+2e-5*Math.sin(o*n),s=Math.atan2(o,r)+3e-6*Math.cos(r*n),i=a*Math.cos(s)+.0065;return{bd_lat:a*Math.sin(s)+.006,bd_lon:i}},formatDateTime:function(t,e){var n=new Date;return Date.prototype.format=function(t){var e={"M+":this.getMonth()+1,"d+":this.getDate(),"h+":this.getHours(),"m+":this.getMinutes(),"s+":this.getSeconds(),"q+":Math.floor((this.getMonth()+3)/3),"S+":this.getMilliseconds()};/(y+)/i.test(t)&&(t=t.replace(RegExp.$1,(this.getFullYear()+"").substr(4-RegExp.$1.length)));for(var n in e)new RegExp("("+n+")").test(t)&&(t=t.replace(RegExp.$1,1==RegExp.$1.length?e[n]:("00"+e[n]).substr((""+e[n]).length)));return t},n.setTime(1e3*t),e=e||"yyyy-MM-dd hh:mm:ss",n.format(e)},isMobile:function(t){return/^1[3|4|5|7|8]{1}[0-9]{9}$/.test(t)},addHost:function(t){return t&&t.indexOf("://")<0&&(t=r.host+(0===t.indexOf("/")?t.substr(1):t)),t},extend:e}; 
 			}); 
		define("app.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";var i=require("./config"),o=require("./utils/util.js"),t=require("./utils/login"),n=require("./utils/session"),e=require("./utils/request");App({onLaunch:function(i){var t=this,n=wx.getExtConfigSync?wx.getExtConfigSync():{};o.isEmpty(n)||(this.globalData.extConfig=n),wx.getSystemInfo({success:function(i){var o=240*i.windowWidth/411;t.globalData.slidePicHeight=o}})},getUserInfo:function(i){var o=this;return new Promise(function(n,e){var u=o;o.globalData.userInfo?("function"==typeof i&&i(o.globalData.userInfo),n(n)):t.login({success:function(o){u.globalData.userInfo=o,"function"==typeof i&&i(u.globalData.userInfo),n(n)},fail:function(i){console.log(i)}})})},onShow:function(i){this.getUserInfo()},getServerInfo:function(o,t,n){var u=arguments.length>3&&void 0!==arguments[3]?arguments[3]:"get";e.request({url:i.host+o,data:t,method:u,success:function(i){n(i)}})},session:function(i){var o=n.get();return o&&i?o[i]:o},jumpThing:function(i){var o=i.currentTarget.dataset.jumptype,t=i.currentTarget.dataset.jumpid;switch(o){case"1":wx.navigateTo({url:"/pages/article/content?id="+t});break;case"2":return;case"3":wx.navigateTo({url:"/pages/form_coupon/content?id="+t});break;case"4":wx.navigateTo({url:"/pages/case/content?id="+t});break;case"5":wx.navigateToMiniProgram({appId:""+t,fail:function(i){console.log("跳转小程序失败"),console.log(i)}});break;case"formPage":wx.navigateTo({url:"/pages/form/form"});break;default:return}},globalData:{slidePicHeight:0,userInfo:null,lawyer:null,wxid:null,extConfig:null,configDatas:{functionConfig:[{txt:"关于我们",pic:"shop/201711/10/o_1bui9tnjd1ps61amou83g041b4h8.png"},{txt:"经典案例",pic:"shop/201711/10/o_1bui9uai55rj1air11bl1q731h0rd.png"},{txt:"工艺流程",pic:"shop/201711/10/o_1bui9ucf81gv5i1frduunh122fi.png"},{txt:"客服在线",pic:"shop/201711/10/o_1bui9ueh49o4111v1oml1cf5c2ln.png"},{txt:"装修知识",pic:"shop/201711/10/o_1bui9ugpf1ccjf561ra9i0q15s9s.png"},{txt:"预约量房",pic:"shop/201711/10/o_1bui9uikg15ai1sde1rvp1gg6vsr11.png"},{txt:"设计团队",pic:"shop/201711/10/o_1bui9ukc5ouj4if18ij95q1poe16.png"},{txt:"优惠活动",pic:"shop/201711/10/o_1bui9um6i186k9ar1iso7gt1ai51b.png"}],picConfig:[{pic:"shop/201711/10/o_1bui821pj4ff1q5emkl16v31elv1g.png",jumpType:"0",jumpTxt:"",jumpId:""},{pic:"shop/201711/10/o_1bui9usei17sc16ma1b831g3r1htr1g.png",jumpType:"0",jumpTxt:"",jumpId:""},{pic:"shop/201711/10/o_1bui827vc1tbn10dg10uncs16231q.png",jumpType:"0",jumpTxt:"",jumpId:""},{pic:"shop/201711/10/o_1bui82am914j617evjfhh47qqu1v.png",jumpType:"0",jumpTxt:"",jumpId:""}],backgroundPic:"shop/201711/10/o_1bui9v3qj1d43eh654u18rqe7n1l.png"}}}); 
 			}); 	require("app.js");
 		__wxRoute = 'pages/index/index';__wxRouteBegin = true; 	define("pages/index/index.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";function e(e,t,a){return t in e?Object.defineProperty(e,t,{value:a,enumerable:!0,configurable:!0,writable:!0}):e[t]=a,e}var t,a=getApp(),i=require("../../utils/util.js"),n=require("../../config.js");Page(i.extend({},(t={data:{imgPre:n.imgPre,host:n.host,configDatas:a.globalData.configDatas,slidePicHeight:a.globalData.slidePicHeight,slidePic:null,case:null,article:null,tel:"",pricePopHide:1,priceButtonHide:1},mekecall:function(){wx.makePhoneCall({phoneNumber:this.data.tel})},onShow:function(){var e=this;a.getServerInfo("WeApp/Template3/getConfigDatas",{},function(t){var n=t.data.configDatas.config_datas;i.isEmpty(n)?e.setData({configDatas:a.globalData.configDatas}):(a.globalData.configDatas=n,n.isShowCalculator&&1==n.isShowCalculator?e.setData({configDatas:n,priceButtonHide:0,pricePopHide:0}):e.setData({configDatas:n}))}),a.getServerInfo("WeApp/Template3/getIndexDatas",{},function(t){e.setData({slidePic:t.data.slidePic,case:t.data.case,article:t.data.article,tel:t.data.tel})}),a.getServerInfo("WeApp/UniDatas/getAppTitle",{},function(e){wx.setNavigationBarTitle({title:e.data.title})})},jumpThing:a.jumpThing,onShareAppMessage:function(){return{}}},e(t,"mekecall",function(){if(""==this.data.tel)return!1;wx.makePhoneCall({phoneNumber:this.data.tel})}),e(t,"onLoad",function(){}),e(t,"pricePopClose",function(){this.setData({pricePopHide:1,priceButtonHide:0})}),e(t,"pricePopShow",function(){this.setData({pricePopHide:0,priceButtonHide:1})}),t))); 
 			}); 	require("pages/index/index.js");
 		__wxRoute = 'pages/form/form';__wxRouteBegin = true; 	define("pages/form/form.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";var t=getApp(),e=require("../../config"),i=require("../../utils/util.js");Page(i.extend({},{data:{warnhidden:!0,imgPre:e.imgPre,configDatas:null,submiting:!0},typeok:function(){wx.showToast({title:"提交成功",duration:2e3})},typewrong:function(){var t=this;this.setData({warnhidden:!1}),setTimeout(function(){t.setData({warnhidden:!0})},2500)},onShow:function(){this.setData({configDatas:t.globalData.configDatas})},formSubmit:function(e){var i=e.detail.value;i.mianji&&/^\d{7,}$/.test(i.tel)&&this.data.submiting?(this.submiting=!1,wx.showLoading({title:"提交中"}),t.getServerInfo("WeApp/Template3/freeSurvey",i,function(t){wx.hideLoading(),wx.showToast({title:"提交成功",icon:"success",duration:2e3}),setTimeout(function(){wx.reLaunch({url:"/pages/index/index"})},1900)})):this.typewrong()},onShareAppMessage:function(){return{}},onLoad:function(){t.getServerInfo("WeApp/UniDatas/getAppTitle",{},function(t){wx.setNavigationBarTitle({title:t.data.title})})}})); 
 			}); 	require("pages/form/form.js");
 		__wxRoute = 'pages/form_coupon/form_coupon';__wxRouteBegin = true; 	define("pages/form_coupon/form_coupon.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";var t=getApp(),e=require("../../config"),i=require("../../utils/util.js");Page(i.extend({},{data:{title:null,imgPre:e.imgPre,contentList:null},onLoad:function(e){var i=this;this.setData({title:e.title}),t.getServerInfo("WeApp/Template3/getContentList",{record_type:e.record_type},function(t){i.setData({contentList:t.data.contentList})}),t.getServerInfo("WeApp/UniDatas/getAppTitle",{},function(t){wx.setNavigationBarTitle({title:t.data.title})})},onShareAppMessage:function(){return{}}})); 
 			}); 	require("pages/form_coupon/form_coupon.js");
 		__wxRoute = 'pages/form_coupon/content';__wxRouteBegin = true; 	define("pages/form_coupon/content.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";var t=getApp();Page({data:{title:"",time:"",content:"",extConfig:t.globalData.extConfig},onLoad:function(e){var n=e.id,a=this;t.getServerInfo("WeApp/Template3/getContentContent",{id:n},function(t){a.setData({title:t.data.content.title,content:t.data.content.content})})},onShareAppMessage:function(){return{}}}); 
 			}); 	require("pages/form_coupon/content.js");
 		__wxRoute = 'pages/form_coupon/form_coupon02';__wxRouteBegin = true; 	define("pages/form_coupon/form_coupon02.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";getApp(),require("../../config");var t=require("../../utils/util.js"),e=require("../../utils/default");Page(t.extend({},e,{data:{warnhidden:!0},typeok:function(){wx.showToast({title:"提交成功",duration:2e3})},typewrong:function(){var t=this;this.setData({warnhidden:!1}),setTimeout(function(){t.setData({warnhidden:!0})},2500)}})); 
 			}); 	require("pages/form_coupon/form_coupon02.js");
 		__wxRoute = 'pages/case/list';__wxRouteBegin = true; 	define("pages/case/list.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";var t=getApp(),e=require("../../config"),a=require("../../utils/util.js");Page(a.extend({},{data:{configDatas:null,caseList:null,imgPre:e.imgPre},onShow:function(){var e=this;this.setData({configDatas:t.globalData.configDatas}),t.getServerInfo("WeApp/Template3/getCaseList",{},function(t){e.setData({caseList:t.data.case})})},onShareAppMessage:function(){return{}},onLoad:function(){t.getServerInfo("WeApp/UniDatas/getAppTitle",{},function(t){wx.setNavigationBarTitle({title:t.data.title})})}})); 
 			}); 	require("pages/case/list.js");
 		__wxRoute = 'pages/case/content';__wxRouteBegin = true; 	define("pages/case/content.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";var t=getApp(),e=require("../../config"),i=require("../../utils/util.js");Page(i.extend({},{data:{imgPre:e.imgPre,pic:null,title:null},onLoad:function(e){var i=this;t.getServerInfo("WeApp/Template3/getCaseContent",{id:e.id},function(t){i.setData({title:t.data.title,pic:t.data.pic})}),t.getServerInfo("WeApp/UniDatas/getAppTitle",{},function(t){wx.setNavigationBarTitle({title:t.data.title})})},onShareAppMessage:function(){return{}}})); 
 			}); 	require("pages/case/content.js");
 		__wxRoute = 'pages/page/page';__wxRouteBegin = true; 	define("pages/page/page.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";var a=getApp(),t=require("../../config.js");Page({data:{slidePicHeight:a.globalData.slidePicHeight,imgPre:t.imgPre,slidePic:null,companyDatas:null},onShow:function(){var t=this;a.getServerInfo("WeApp/Template3/getPageDatas",{},function(a){t.setData({slidePic:a.data.slidePic,companyDatas:a.data.companyDatas})})},openMap:function(){wx.openLocation({latitude:parseFloat(this.data.companyDatas.x),longitude:parseFloat(this.data.companyDatas.y),scale:28})},jumpThing:a.jumpThing,onShareAppMessage:function(){return{}},onLoad:function(){a.getServerInfo("WeApp/UniDatas/getAppTitle",{},function(a){wx.setNavigationBarTitle({title:a.data.title})})}}); 
 			}); 	require("pages/page/page.js");
 		__wxRoute = 'pages/article/list';__wxRouteBegin = true; 	define("pages/article/list.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";var t=getApp();require("../../config.js");Page({data:{configDatas:null,articleList:null},onShow:function(){var a=this;this.setData({configDatas:t.globalData.configDatas}),t.getServerInfo("WeApp/Template3/getArticleList",{},function(t){a.setData({articleList:t.data.article})})},onShareAppMessage:function(){return{}},onLoad:function(){t.getServerInfo("WeApp/UniDatas/getAppTitle",{},function(t){wx.setNavigationBarTitle({title:t.data.title})})}}); 
 			}); 	require("pages/article/list.js");
 		__wxRoute = 'pages/article/content';__wxRouteBegin = true; 	define("pages/article/content.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";var t=getApp();Page({data:{title:null,time:null,content:null},onLoad:function(e){var n=this;t.getServerInfo("WeApp/Template3/getArticleContent",{id:e.id},function(t){n.setData({title:t.data.title,time:t.data.addtime,content:t.data.content})}),t.getServerInfo("WeApp/UniDatas/getAppTitle",{},function(t){wx.setNavigationBarTitle({title:t.data.title})})},onShareAppMessage:function(){return{}}}); 
 			}); 	require("pages/article/content.js");
 		__wxRoute = 'pages/calculator/calculator';__wxRouteBegin = true; 	define("pages/calculator/calculator.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
"use strict";var a=getApp();Page({data:{items:[{name:"经济环保",value:"经济环保"},{name:"舒适装修",value:"舒适装修",checked:!0},{name:"轻奢装修",value:"轻奢装修"}],multiArray:[["全部","历下区","市中区","槐荫区","天桥区","历城区"],["所在小区"]],objectMultiArray:[[{id:0,name:"全部"},{id:1,name:"历下区"},{id:2,name:"市中区"},{id:3,name:"槐荫区"},{id:4,name:"天桥区"},{id:5,name:"历城区"}],[{id:0,name:"所在小区"}]],multiIndex:[0,0],submiting:!1},bindMultiPickerColumnChange:function(a){console.log("修改的列为",a.detail.column,"，值为",a.detail.value);var e={multiArray:this.data.multiArray,multiIndex:this.data.multiIndex};switch(e.multiIndex[a.detail.column]=a.detail.value,a.detail.column){case 0:switch(e.multiIndex[0]){case 0:e.multiArray[1]=["所在小区"];break;case 1:e.multiArray[1]=["历下小区01","历下小区02","历下小区03"];break;case 2:e.multiArray[1]=["市中小区01","市中小区02"];break;case 3:e.multiArray[1]=["槐荫小区01","槐荫小区02","槐荫小区03"];break;case 4:e.multiArray[1]=["天桥小区01","天桥小区02"];break;case 5:e.multiArray[1]=["历城小区01","历城小区02","历城小区03"]}e.multiIndex[1]=0}this.setData(e)},formSubmit:function(e){var i=e.detail.value;i.mianji&&/^1\d{10}$/.test(i.tel)&&i.address&&i.fangshi&&!this.data.submiting?(this.submiting=!0,wx.showLoading({title:"提交中"}),a.getServerInfo("WeApp/UniDatas/calculateSubmit",i,function(a){wx.hideLoading(),wx.showToast({title:"提交成功",icon:"success",duration:2e3}),setTimeout(function(){wx.reLaunch({url:"/pages/index/index"})},1900)})):wx.showToast({title:"字段填写错误",icon:"none"})}}); 
 			}); 	require("pages/calculator/calculator.js");
 	